default: &default
  pool: 5
  timeout: 5000
  adapter: postgresql
  encoding: unicode
  database: metova
<% unless ENV['TRAVIS'] %>
  username: apps
  password: metova123
  host: localhost
<% end %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
